name: Package

on: push

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 9.8.0

      - run: pnpm install --frozen-lockfile

      - run: pnpm run package:server

      - uses: actions/upload-artifact@v3
        with:
          name: StudioPresence-Windows
          path: |
            release/studiopresence-win*.exe
            release/startup.vbs

      - uses: actions/upload-artifact@v3
        with:
          name: StudioPresence-macOS
          path: release/studiopresence-macos*

      - uses: actions/upload-artifact@v3
        with:
          name: StudioPresence-Linux
          path: release/studiopresence-linux*

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 9.8.0

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: mkdir release

      - run: pnpm install --frozen-lockfile

      - run: pnpm build:client

      - uses: actions/upload-artifact@v3
        with:
          name: StudioPresence-Plugin
          path: release/studiopresence*.rbxm
